function profit_est_appro_der1 = profit_est_derivative1(T)
%PROFIT_EST_DERIVATIVE1
%    PROFIT_EST_APPRO_DER1 = PROFIT_EST_DERIVATIVE1(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-09-28 23:22:12

t2 = 1.0./T.^2;
t3 = T.*7.485687543625216e-2;
t4 = -t3;
t5 = exp(t4);
profit_est_appro_der1 = t2.*1.0e+2+t2.*(t5.*5.984525432619786e+3-5.984525432619786e+3)+(t5.*4.479828748547024e+2)./T;
end
