function profit_est_approx_der1 = profit_est_approx_derivative1(T)
%PROFIT_EST_APPROX_DERIVATIVE1
%    PROFIT_EST_APPROX_DER1 = PROFIT_EST_APPROX_DERIVATIVE1(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-07-01 22:14:50

profit_est_approx_der1 = 1.0./T.^2.*1.0e+2-5.984385273379854e-1;
end
