function profit_est_approx_der1 = profit_est_derivative1(T)
%PROFIT_EST_DERIVATIVE1
%    PROFIT_EST_APPROX_DER1 = PROFIT_EST_DERIVATIVE1(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-07-01 22:14:50

t2 = 1.0./T;
t4 = T.*2.013748777339802e-2;
t6 = T.*8.346553805058627e-3;
t3 = t2.^2;
t5 = -t4;
t8 = -t6;
t7 = exp(t5);
t9 = exp(t8);
et1 = t3.*1.0e+2+t2.*t7.*8.573657646512377e+1-t2.*t9.*6.34563938595186e+1;
et2 = -t3.*(t9.*7.602705900135616e+3-7.602705900135616e+3)+t3.*(t7.*4.257560696244509e+3-4.257560696244509e+3);
profit_est_approx_der1 = et1+et2;
end
