function profit_simu_der1 = profit_simu_derivative1(T)
%PROFIT_SIMU_DERIVATIVE1
%    PROFIT_SIMU_DER1 = PROFIT_SIMU_DERIVATIVE1(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-07-01 22:14:49

t2 = 1.0./T;
t4 = T./5.0e+1;
t6 = T./1.0e+2;
t3 = t2.^2;
t5 = -t4;
t8 = -t6;
t7 = exp(t5);
t9 = exp(t8);
profit_simu_der1 = t3.*1.0e+2+t3.*(t7.*4.8e+3-4.8e+3)-t3.*(t9.*7.2e+3-7.2e+3)+t2.*t7.*9.6e+1-t2.*t9.*7.2e+1;
end
