function profit_true_der2 = profit_true_derivative2(T)
%PROFIT_TRUE_DERIVATIVE2
%    PROFIT_TRUE_DER2 = PROFIT_TRUE_DERIVATIVE2(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-09-28 23:22:11

t2 = 1.0./T.^3;
t3 = T.*(2.0./2.5e+1);
t4 = -t3;
t5 = exp(t4);
profit_true_der2 = t2.*-2.0e+2-t2.*(t5.*5.3125e+3-5.3125e+3).*2.0-(t5.*3.4e+1)./T-1.0./T.^2.*t5.*8.5e+2;
end
