function profit_est_approx_der2 = profit_est_approx_derivative2(T)
%PROFIT_EST_APPROX_DERIVATIVE2
%    PROFIT_EST_APPROX_DER2 = PROFIT_EST_APPROX_DERIVATIVE2(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-07-01 22:14:50

profit_est_approx_der2 = 1.0./T.^3.*-2.0e+2;
end
