function profit_appro_der1 = profit_true_appro_derivative1(T)
%PROFIT_TRUE_APPRO_DERIVATIVE1
%    PROFIT_APPRO_DER1 = PROFIT_TRUE_APPRO_DERIVATIVE1(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-09-28 23:22:12

profit_appro_der1 = 1.0./T.^2.*1.0e+2-1.7e+1;
end
