function profit_est_appro_der2 = profit_est_appro_derivative2(T)
%PROFIT_EST_APPRO_DERIVATIVE2
%    PROFIT_EST_APPRO_DER2 = PROFIT_EST_APPRO_DERIVATIVE2(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-09-28 23:22:12

profit_est_appro_der2 = 1.0./T.^3.*-2.0e+2;
end
