function profit_est_appro_der1 = profit_est_appro_derivative1(T)
%PROFIT_EST_APPRO_DERIVATIVE1
%    PROFIT_EST_APPRO_DER1 = PROFIT_EST_APPRO_DERIVATIVE1(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-09-28 23:22:12

profit_est_appro_der1 = 1.0./T.^2.*1.0e+2-1.67672991302863e+1;
end
