function profit_der2 = profit_derivative2(T)
%PROFIT_DERIVATIVE2
%    PROFIT_DER2 = PROFIT_DERIVATIVE2(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-06-25 20:51:12

t2 = 1.0./T;
t5 = T./5.0e+1;
t7 = T.*(3.0./1.0e+2);
t3 = t2.^2;
t4 = t2.^3;
t6 = -t5;
t9 = -t7;
t8 = exp(t6);
t10 = exp(t9);
profit_der2 = t4.*-2.0e+2-t4.*(t10.*3.2e+3-3.2e+3).*2.0+t4.*(t8.*3.6e+3-3.6e+3).*2.0+t2.*t8.*(3.6e+1./2.5e+1)+t3.*t8.*1.44e+2-t2.*t10.*(7.2e+1./2.5e+1)-t3.*t10.*1.92e+2;
end
