function profit_true_der1 = profit_true_derivative1(T)
%PROFIT_TRUE_DERIVATIVE1
%    PROFIT_TRUE_DER1 = PROFIT_TRUE_DERIVATIVE1(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-07-01 22:14:36

t2 = 1.0./T.^2;
t3 = T./5.0e+1;
t4 = -t3;
t5 = exp(t4);
profit_true_der1 = t2.*1.0e+2+t2.*(t5.*4.2e+3-4.2e+3)+(t5.*8.4e+1)./T;
end
